import {
  User,
  Customer,
  Category,
  VariantType,
  Product,
  Quote,
  QuoteSettings,
} from '../types';

export const INITIAL_USERS: User[] = [
  {
    id: 'usr_admin',
    email: 'admin@brandedsolutions.co.za',
    name: 'Sarah Jenkins (Admin)',
    role: 'ADMIN',
    isActive: true,
    requiresPasswordChange: false,
    createdAt: '2026-01-10T08:00:00Z',
    updatedAt: '2026-01-10T08:00:00Z',
  },
  {
    id: 'usr_staff1',
    email: 'staff@brandedsolutions.co.za',
    name: 'Sipho Ndlovu (Staff)',
    role: 'STAFF',
    isActive: true,
    requiresPasswordChange: false,
    createdAt: '2026-02-01T09:00:00Z',
    updatedAt: '2026-02-01T09:00:00Z',
  },
  {
    id: 'usr_staff2',
    email: 'sales@brandedsolutions.co.za',
    name: 'Lindiwe Botha (Sales)',
    role: 'STAFF',
    isActive: true,
    requiresPasswordChange: false,
    createdAt: '2026-02-15T10:00:00Z',
    updatedAt: '2026-02-15T10:00:00Z',
  },
];

export const INITIAL_SETTINGS: QuoteSettings = {
  staffDiscountCeiling: 500, // Max R500 manual discount for Staff
  quoteValidityDays: 30,
  termsAndConditions:
    '1. 50% deposit required on quote acceptance prior to production.\n2. Balance due prior to dispatch.\n3. Artwork approval required in writing.\n4. Prices valid for 30 days from quote date.\n5. Standard lead time: 7-10 business days from artwork sign-off.',
  senderEmail: 'quotes@brandedsolutions.co.za',
  senderName: 'Branded Solutions SA',
  refPrefix: 'QS-',
  refPattern: 'AMBIGUITY_SAFE',
  companyName: 'Branded Solutions South Africa (Pty) Ltd',
  companyAddress: '42 Enterprise Boulevard, Sandton, Johannesburg, 2196',
  companyPhone: '+27 (0)11 555 0199',
  companyVatNumber: '4820192831',
};

export const INITIAL_CUSTOMERS: Customer[] = [
  {
    id: 'cust_0',
    companyName: 'Active Ops',
    contactName: 'Ntokozo Mhlabane',
    email: 'ntokozo.mhlabane@activeops.co.za',
    phone: '+27 82 999 1234',
    vatNumber: '4770192811',
    address: {
      street: '15 West Street',
      city: 'Sandton',
      province: 'Gauteng',
      postalCode: '2196',
    },
    createdAt: '2026-03-01T08:00:00Z',
  },
  {
    id: 'cust_1',
    companyName: 'Nedbank Corporate Events',
    contactName: 'Thabo Mokoena',
    email: 'thabo.mokoena@nedbank.co.za',
    phone: '+27 82 555 1234',
    vatNumber: '4010192834',
    address: {
      street: '135 Rivonia Road',
      city: 'Sandton',
      province: 'Gauteng',
      postalCode: '2196',
    },
    createdAt: '2026-01-15T10:00:00Z',
  },
  {
    id: 'cust_2',
    companyName: 'Vodacom Marketing Group',
    contactName: 'Annelize Van Der Merwe',
    email: 'annelize.vdm@vodacom.co.za',
    phone: '+27 83 444 9876',
    vatNumber: '4120883921',
    address: {
      street: 'Vodacom Corporate Park, 082 Vodacom Blvd',
      city: 'Midrand',
      province: 'Gauteng',
      postalCode: '1685',
    },
    createdAt: '2026-01-18T11:30:00Z',
  },
];

export const INITIAL_CATEGORIES: Category[] = [
  {
    id: 'cat_clothing',
    name: 'Apparel & Clothing',
    description: 'Custom branded garments, t-shirts, polos, hoodies, workwear and jackets.',
    parentId: null,
    isActive: true,
    slug: 'apparel-clothing',
  },
  {
    id: 'cat_tshirts',
    name: 'T-Shirts',
    description: 'Cotton, promo, performance, and organic t-shirts.',
    parentId: 'cat_clothing',
    isActive: true,
    slug: 't-shirts',
  },
  {
    id: 'cat_polos',
    name: 'Polo Shirts & Golfers',
    description: 'Corporate pique cotton and performance golf shirts.',
    parentId: 'cat_clothing',
    isActive: true,
    slug: 'polo-shirts-golfers',
  },
  {
    id: 'cat_outerwear',
    name: 'Hoodies & Jackets',
    description: 'Warm corporate fleeces, hoodies, softshell jackets, and vests.',
    parentId: 'cat_clothing',
    isActive: true,
    slug: 'hoodies-jackets',
  },
  {
    id: 'cat_workwear',
    name: 'Workwear & Safety Gear',
    description: 'High-visibility safety vests, overalls, and protective clothing.',
    parentId: 'cat_clothing',
    isActive: true,
    slug: 'workwear-safety',
  },
  {
    id: 'cat_drinkware',
    name: 'Bags & Drinkware',
    description: 'Water bottles, mugs, tote bags, and backpacks.',
    parentId: null,
    isActive: true,
    slug: 'bags-drinkware',
  },
  {
    id: 'cat_bottles',
    name: 'Water Bottles & Mugs',
    description: 'Insulated flasks, travel mugs, and ceramic coffee mugs.',
    parentId: 'cat_drinkware',
    isActive: true,
    slug: 'water-bottles-mugs',
  },
  {
    id: 'cat_totes',
    name: 'Tote Bags & Shoppers',
    description: 'Eco cotton totes and branded shopper bags.',
    parentId: 'cat_drinkware',
    isActive: true,
    slug: 'tote-bags-shoppers',
  },
  {
    id: 'cat_backpacks',
    name: 'Backpacks & Laptop Bags',
    description: 'Executive laptop backpacks, drawstring bags, and conference bags.',
    parentId: 'cat_drinkware',
    isActive: true,
    slug: 'backpacks-laptop-bags',
  },
  {
    id: 'cat_stationery',
    name: 'Promotional & Executive Giftware',
    description: 'Hardcover notebooks, pen sets, lanyards, and gift packages.',
    parentId: null,
    isActive: true,
    slug: 'promotional-giftware',
  },
  {
    id: 'cat_tech',
    name: 'Tech & Power Banks',
    description: 'Power banks, USB flash drives, wireless chargers, and speakers.',
    parentId: 'cat_stationery',
    isActive: true,
    slug: 'tech-powerbanks',
  },
];

export const INITIAL_VARIANTS: VariantType[] = [
  {
    id: 'var_size',
    name: 'Garment Size',
    isReusable: true,
    values: [
      { id: 'v_size_s', name: 'Small (S)', skuSuffix: 'S', priceDelta: 0 },
      { id: 'v_size_m', name: 'Medium (M)', skuSuffix: 'M', priceDelta: 0 },
      { id: 'v_size_l', name: 'Large (L)', skuSuffix: 'L', priceDelta: 0 },
      { id: 'v_size_xl', name: 'Extra Large (XL)', skuSuffix: 'XL', priceDelta: 0 },
      { id: 'v_size_2xl', name: '2X Large (2XL)', skuSuffix: '2XL', priceDelta: 12.50 },
      { id: 'v_size_3xl', name: '3X Large (3XL)', skuSuffix: '3XL', priceDelta: 25.00 },
    ],
  },
  {
    id: 'var_colour',
    name: 'Primary Colour',
    isReusable: true,
    values: [
      { id: 'v_col_black', name: 'Jet Black', skuSuffix: 'BLK', priceDelta: 0 },
      { id: 'v_col_white', name: 'Pure White', skuSuffix: 'WHT', priceDelta: 0 },
      { id: 'v_col_navy', name: 'Navy Blue', skuSuffix: 'NVY', priceDelta: 0 },
      { id: 'v_col_red', name: 'Crimson Red', skuSuffix: 'RED', priceDelta: 0 },
      { id: 'v_col_green', name: 'Bottle Green', skuSuffix: 'GRN', priceDelta: 0 },
      { id: 'v_col_grey', name: 'Heather Grey', skuSuffix: 'GRY', priceDelta: 0 },
    ],
  },
  {
    id: 'var_branding',
    name: 'Branding Location & Technique',
    isReusable: true,
    values: [
      { id: 'v_brand_none', name: 'Blank / Unbranded', skuSuffix: 'BLANK', priceDelta: 0 },
      { id: 'v_brand_screen_front', name: 'Screen Print - 1 Position Front', skuSuffix: 'SPF', priceDelta: 18.00 },
      { id: 'v_brand_screen_front_back', name: 'Screen Print - Front & Back', skuSuffix: 'SPFB', priceDelta: 32.00 },
      { id: 'v_brand_embroidery', name: 'Embroidery - Left Chest Logo', skuSuffix: 'EMB', priceDelta: 38.00 },
    ],
  },
];

export const INITIAL_PRODUCTS: Product[] = [
  // --- T-SHIRTS CATEGORY ---
  {
    id: 'prod_tsh_1',
    sku: 'TSH-160',
    name: 'Basic Cotton T-Shirt 160g',
    description: '100% carded cotton single jersey fabric. Double needle finish on hem and sleeves. Ideal for high-volume promo giveaways.',
    basePrice: 85.00,
    categoryId: 'cat_tshirts',
    isActive: true,
    images: [
      'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1622445268465-843d63d0f63f?w=800&auto=format&fit=crop&q=80',
    ],
    volumeTiers: [
      { id: 'vt_1_1', minQuantity: 1, maxQuantity: 24, discountPercentage: 0 },
      { id: 'vt_1_2', minQuantity: 25, maxQuantity: 49, discountPercentage: 5 },
      { id: 'vt_1_3', minQuantity: 50, maxQuantity: 99, discountPercentage: 12 },
      { id: 'vt_1_4', minQuantity: 100, maxQuantity: 249, discountPercentage: 20 },
      { id: 'vt_1_5', minQuantity: 250, maxQuantity: null, discountPercentage: 28 },
    ],
    variantTypeIds: ['var_size', 'var_colour', 'var_branding'],
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'prod_tsh_2',
    sku: 'TSH-200',
    name: 'Premium Heavyweight Cotton T-Shirt 200g',
    description: 'Ultra-soft 200g combed ring-spun cotton. Premium retail fit with taped neck and shoulders for durability.',
    basePrice: 120.00,
    categoryId: 'cat_tshirts',
    isActive: true,
    images: [
      'https://images.unsplash.com/photo-1618354691373-d851c5c3a990?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1529374255404-311a2a4f1fd9?w=800&auto=format&fit=crop&q=80',
    ],
    volumeTiers: [
      { id: 'vt_2_1', minQuantity: 1, maxQuantity: 19, discountPercentage: 0 },
      { id: 'vt_2_2', minQuantity: 20, maxQuantity: 49, discountPercentage: 8 },
      { id: 'vt_2_3', minQuantity: 50, maxQuantity: 99, discountPercentage: 15 },
      { id: 'vt_2_4', minQuantity: 100, maxQuantity: null, discountPercentage: 25 },
    ],
    variantTypeIds: ['var_size', 'var_colour', 'var_branding'],
    createdAt: '2026-01-05T00:00:00Z',
    updatedAt: '2026-01-05T00:00:00Z',
  },
  {
    id: 'prod_tsh_3',
    sku: 'TSH-CREW',
    name: 'Slim-Fit Crew Neck Promotional T-Shirt',
    description: 'Modern fitted cut 170g combed cotton with elastane neck rib. Stylish modern aesthetic for corporate events.',
    basePrice: 95.00,
    categoryId: 'cat_tshirts',
    isActive: true,
    images: [
      'https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?w=800&auto=format&fit=crop&q=80',
    ],
    volumeTiers: [
      { id: 'vt_3_1', minQuantity: 1, maxQuantity: 24, discountPercentage: 0 },
      { id: 'vt_3_2', minQuantity: 25, maxQuantity: 99, discountPercentage: 10 },
      { id: 'vt_3_3', minQuantity: 100, maxQuantity: null, discountPercentage: 22 },
    ],
    variantTypeIds: ['var_size', 'var_colour', 'var_branding'],
    createdAt: '2026-01-06T00:00:00Z',
    updatedAt: '2026-01-06T00:00:00Z',
  },
  {
    id: 'prod_tsh_4',
    sku: 'TSH-VNECK',
    name: 'V-Neck Executive Cotton T-Shirt',
    description: '175g soft-touch ring-spun cotton V-neck. Taped neck collar and twin-needle hems.',
    basePrice: 110.00,
    categoryId: 'cat_tshirts',
    isActive: true,
    images: [
      'https://images.unsplash.com/photo-1562157873-818bc0726f68?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?w=800&auto=format&fit=crop&q=80',
    ],
    volumeTiers: [
      { id: 'vt_4_1', minQuantity: 1, maxQuantity: 24, discountPercentage: 0 },
      { id: 'vt_4_2', minQuantity: 25, maxQuantity: 99, discountPercentage: 12 },
      { id: 'vt_4_3', minQuantity: 100, maxQuantity: null, discountPercentage: 22 },
    ],
    variantTypeIds: ['var_size', 'var_colour', 'var_branding'],
    createdAt: '2026-01-07T00:00:00Z',
    updatedAt: '2026-01-07T00:00:00Z',
  },
  {
    id: 'prod_tsh_5',
    sku: 'TSH-LS180',
    name: 'Long Sleeve Cotton T-Shirt 180g',
    description: '180g 100% cotton long sleeve tee with ribbed cuffs. Excellent coverage for cooler outdoor team events.',
    basePrice: 145.00,
    categoryId: 'cat_tshirts',
    isActive: true,
    images: [
      'https://images.unsplash.com/photo-1622445268465-843d63d0f63f?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1618354691373-d851c5c3a990?w=800&auto=format&fit=crop&q=80',
    ],
    volumeTiers: [
      { id: 'vt_5_1', minQuantity: 1, maxQuantity: 19, discountPercentage: 0 },
      { id: 'vt_5_2', minQuantity: 20, maxQuantity: 49, discountPercentage: 10 },
      { id: 'vt_5_3', minQuantity: 50, maxQuantity: null, discountPercentage: 20 },
    ],
    variantTypeIds: ['var_size', 'var_colour', 'var_branding'],
    createdAt: '2026-01-08T00:00:00Z',
    updatedAt: '2026-01-08T00:00:00Z',
  },
  {
    id: 'prod_tsh_6',
    sku: 'TSH-DRYFIT',
    name: 'Athletic Quick-Dry Moisture-Wicking T-Shirt',
    description: '140g high-tech polyester sports mesh. Breathable, quick-drying fabric for golf days, sports teams and outdoor marathons.',
    basePrice: 130.00,
    categoryId: 'cat_tshirts',
    isActive: true,
    images: [
      'https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?w=800&auto=format&fit=crop&q=80',
    ],
    volumeTiers: [
      { id: 'vt_6_1', minQuantity: 1, maxQuantity: 24, discountPercentage: 0 },
      { id: 'vt_6_2', minQuantity: 25, maxQuantity: 99, discountPercentage: 15 },
      { id: 'vt_6_3', minQuantity: 100, maxQuantity: null, discountPercentage: 25 },
    ],
    variantTypeIds: ['var_size', 'var_colour', 'var_branding'],
    createdAt: '2026-01-09T00:00:00Z',
    updatedAt: '2026-01-09T00:00:00Z',
  },
  {
    id: 'prod_tsh_7',
    sku: 'TSH-ORGANIC',
    name: '100% Organic Eco-Cotton T-Shirt',
    description: 'GOTS-certified organic ring-spun combed cotton 180g. Eco-friendly sustainability option with soft hand feel.',
    basePrice: 150.00,
    categoryId: 'cat_tshirts',
    isActive: true,
    images: [
      'https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=800&auto=format&fit=crop&q=80',
    ],
    volumeTiers: [
      { id: 'vt_7_1', minQuantity: 1, maxQuantity: 19, discountPercentage: 0 },
      { id: 'vt_7_2', minQuantity: 20, maxQuantity: 49, discountPercentage: 10 },
      { id: 'vt_7_3', minQuantity: 50, maxQuantity: null, discountPercentage: 20 },
    ],
    variantTypeIds: ['var_size', 'var_colour', 'var_branding'],
    createdAt: '2026-01-10T00:00:00Z',
    updatedAt: '2026-01-10T00:00:00Z',
  },

  // --- POLO SHIRTS & GOLFBAGS ---
  {
    id: 'prod_polo_1',
    sku: 'POLO-220',
    name: 'Classic Pique Cotton Polo Shirt',
    description: 'Heavyweight 220g combed cotton pique knit polo. Ribbed collar and cuffs with matching buttons.',
    basePrice: 175.00,
    categoryId: 'cat_polos',
    isActive: true,
    images: [
      'https://images.unsplash.com/photo-1625910513413-41315e98585e?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1581655353564-df123a1eb820?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1586363104862-3a5e2ab60d99?w=800&auto=format&fit=crop&q=80',
    ],
    volumeTiers: [
      { id: 'vt_p1_1', minQuantity: 1, maxQuantity: 14, discountPercentage: 0 },
      { id: 'vt_p1_2', minQuantity: 15, maxQuantity: 49, discountPercentage: 7 },
      { id: 'vt_p1_3', minQuantity: 50, maxQuantity: 99, discountPercentage: 15 },
      { id: 'vt_p1_4', minQuantity: 100, maxQuantity: null, discountPercentage: 22 },
    ],
    variantTypeIds: ['var_size', 'var_colour', 'var_branding'],
    createdAt: '2026-01-11T00:00:00Z',
    updatedAt: '2026-01-11T00:00:00Z',
  },
  {
    id: 'prod_polo_2',
    sku: 'GOLF-PRO',
    name: 'Moisture-Wicking Executive Golf Shirt',
    description: '160g poly-spandex moisture management fabric. Wrinkle resistant with self-fabric collar for high performance executive wear.',
    basePrice: 210.00,
    categoryId: 'cat_polos',
    isActive: true,
    images: [
      'https://images.unsplash.com/photo-1586363104862-3a5e2ab60d99?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1625910513413-41315e98585e?w=800&auto=format&fit=crop&q=80',
    ],
    volumeTiers: [
      { id: 'vt_p2_1', minQuantity: 1, maxQuantity: 14, discountPercentage: 0 },
      { id: 'vt_p2_2', minQuantity: 15, maxQuantity: 49, discountPercentage: 10 },
      { id: 'vt_p2_3', minQuantity: 50, maxQuantity: null, discountPercentage: 20 },
    ],
    variantTypeIds: ['var_size', 'var_colour', 'var_branding'],
    createdAt: '2026-01-12T00:00:00Z',
    updatedAt: '2026-01-12T00:00:00Z',
  },

  // --- HOODIES & JACKETS ---
  {
    id: 'prod_hod_1',
    sku: 'HOD-300',
    name: 'Fleece Hooded Sweater / Hoodie',
    description: '300g brushed fleece hoodie with kangaroo pocket and shoelace drawstring.',
    basePrice: 320.00,
    categoryId: 'cat_outerwear',
    isActive: true,
    images: [
      'https://images.unsplash.com/photo-1556905055-8f358a7a47b2?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1509967419530-da38b4704bc6?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1578632767115-351597cf2477?w=800&auto=format&fit=crop&q=80',
    ],
    volumeTiers: [
      { id: 'vt_h1_1', minQuantity: 1, maxQuantity: 9, discountPercentage: 0 },
      { id: 'vt_h1_2', minQuantity: 10, maxQuantity: 29, discountPercentage: 10 },
      { id: 'vt_h1_3', minQuantity: 30, maxQuantity: 74, discountPercentage: 18 },
      { id: 'vt_h1_4', minQuantity: 75, maxQuantity: null, discountPercentage: 25 },
    ],
    variantTypeIds: ['var_size', 'var_colour', 'var_branding'],
    createdAt: '2026-01-13T00:00:00Z',
    updatedAt: '2026-01-13T00:00:00Z',
  },
  {
    id: 'prod_jck_1',
    sku: 'JCK-SOFT',
    name: 'Softshell All-Weather Jacket',
    description: '3-layer bonded softshell jacket. Windproof, water-resistant with fleece interior.',
    basePrice: 580.00,
    categoryId: 'cat_outerwear',
    isActive: true,
    images: [
      'https://images.unsplash.com/photo-1544441893-675973e31985?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1608256246200-53e635b5b65f?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1512436991641-6745cdb1723f?w=800&auto=format&fit=crop&q=80',
    ],
    volumeTiers: [
      { id: 'vt_j1_1', minQuantity: 1, maxQuantity: 9, discountPercentage: 0 },
      { id: 'vt_j1_2', minQuantity: 10, maxQuantity: 24, discountPercentage: 8 },
      { id: 'vt_j1_3', minQuantity: 25, maxQuantity: null, discountPercentage: 18 },
    ],
    variantTypeIds: ['var_size', 'var_colour', 'var_branding'],
    createdAt: '2026-01-14T00:00:00Z',
    updatedAt: '2026-01-14T00:00:00Z',
  },

  // --- WORKWEAR ---
  {
    id: 'prod_wrk_1',
    sku: 'VIS-VEST',
    name: 'High-Visibility Reflective Safety Vest',
    description: 'Class 2 reflective safety vest with zip front and clear ID card holder pocket. Essential for construction and site visits.',
    basePrice: 75.00,
    categoryId: 'cat_workwear',
    isActive: true,
    images: [
      'https://images.unsplash.com/photo-1588850561407-ed78c282e89b?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1534215754734-18e55d13e346?w=800&auto=format&fit=crop&q=80',
    ],
    volumeTiers: [
      { id: 'vt_w1_1', minQuantity: 1, maxQuantity: 24, discountPercentage: 0 },
      { id: 'vt_w1_2', minQuantity: 25, maxQuantity: 99, discountPercentage: 12 },
      { id: 'vt_w1_3', minQuantity: 100, maxQuantity: null, discountPercentage: 25 },
    ],
    variantTypeIds: ['var_size', 'var_branding'],
    createdAt: '2026-01-15T00:00:00Z',
    updatedAt: '2026-01-15T00:00:00Z',
  },

  // --- CAPS & HEADWEAR ---
  {
    id: 'prod_cap_1',
    sku: 'CAP-6P',
    name: '6-Panel Brushed Cotton Cap',
    description: 'Heavy brushed cotton cap with pre-curved peak and metal clasp closure. Perfect for outdoor branding.',
    basePrice: 65.00,
    categoryId: 'cat_clothing',
    isActive: true,
    images: [
      'https://images.unsplash.com/photo-1588850561407-ed78c282e89b?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1534215754734-18e55d13e346?w=800&auto=format&fit=crop&q=80',
    ],
    volumeTiers: [
      { id: 'vt_c1_1', minQuantity: 1, maxQuantity: 49, discountPercentage: 0 },
      { id: 'vt_c1_2', minQuantity: 50, maxQuantity: 99, discountPercentage: 10 },
      { id: 'vt_c1_3', minQuantity: 100, maxQuantity: null, discountPercentage: 20 },
    ],
    variantTypeIds: ['var_colour', 'var_branding'],
    createdAt: '2026-01-16T00:00:00Z',
    updatedAt: '2026-01-16T00:00:00Z',
  },

  // --- DRINKWARE & BAGS ---
  {
    id: 'prod_bot_1',
    sku: 'BOT-750',
    name: 'Stainless Steel Vacuum Insulated Water Bottle 750ml',
    description: 'Double-wall stainless steel thermal flask. Keeps beverages hot for 12 hrs or cold for 24 hrs.',
    basePrice: 185.00,
    categoryId: 'cat_bottles',
    isActive: true,
    images: [
      'https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1523362628745-0c100150b504?w=800&auto=format&fit=crop&q=80',
    ],
    volumeTiers: [
      { id: 'vt_b1_1', minQuantity: 1, maxQuantity: 24, discountPercentage: 0 },
      { id: 'vt_b1_2', minQuantity: 25, maxQuantity: 74, discountPercentage: 10 },
      { id: 'vt_b1_3', minQuantity: 75, maxQuantity: null, discountPercentage: 20 },
    ],
    variantTypeIds: ['var_colour'],
    createdAt: '2026-01-17T00:00:00Z',
    updatedAt: '2026-01-17T00:00:00Z',
  },
  {
    id: 'prod_mug_1',
    sku: 'MUG-330',
    name: 'Ceramic Promotional Coffee Mug 330ml',
    description: 'High-gloss AAA grade ceramic mug suitable for full-colour wrap dye sublimation.',
    basePrice: 48.00,
    categoryId: 'cat_bottles',
    isActive: true,
    images: [
      'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1577937927133-66ef06acdf18?w=800&auto=format&fit=crop&q=80',
    ],
    volumeTiers: [
      { id: 'vt_m1_1', minQuantity: 1, maxQuantity: 35, discountPercentage: 0 },
      { id: 'vt_m1_2', minQuantity: 36, maxQuantity: 99, discountPercentage: 12 },
      { id: 'vt_m1_3', minQuantity: 100, maxQuantity: null, discountPercentage: 25 },
    ],
    variantTypeIds: ['var_colour'],
    createdAt: '2026-01-18T00:00:00Z',
    updatedAt: '2026-01-18T00:00:00Z',
  },
  {
    id: 'prod_bag_1',
    sku: 'BAG-TOT',
    name: 'Heavy-Duty Eco Cotton Tote Bag',
    description: '220g unbleached natural cotton tote bag with reinforced long handles.',
    basePrice: 42.00,
    categoryId: 'cat_totes',
    isActive: true,
    images: [
      'https://images.unsplash.com/photo-1597484662315-c80138d04f4b?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1544816155-12df9643f363?w=800&auto=format&fit=crop&q=80',
    ],
    volumeTiers: [
      { id: 'vt_bg1_1', minQuantity: 1, maxQuantity: 49, discountPercentage: 0 },
      { id: 'vt_bg1_2', minQuantity: 50, maxQuantity: 199, discountPercentage: 15 },
      { id: 'vt_bg1_3', minQuantity: 200, maxQuantity: null, discountPercentage: 28 },
    ],
    variantTypeIds: ['var_branding'],
    createdAt: '2026-01-19T00:00:00Z',
    updatedAt: '2026-01-19T00:00:00Z',
  },
  {
    id: 'prod_bag_2',
    sku: 'BAG-LAP',
    name: 'Executive Padded Laptop Backpack 15.6"',
    description: 'Water-resistant 600D polyester with dedicated padded laptop compartment, USB charging port, and ergonomic shoulder straps.',
    basePrice: 380.00,
    categoryId: 'cat_backpacks',
    isActive: true,
    images: [
      'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1622560480605-d83c853bc5c3?w=800&auto=format&fit=crop&q=80',
    ],
    volumeTiers: [
      { id: 'vt_bg2_1', minQuantity: 1, maxQuantity: 19, discountPercentage: 0 },
      { id: 'vt_bg2_2', minQuantity: 20, maxQuantity: 49, discountPercentage: 10 },
      { id: 'vt_bg2_3', minQuantity: 50, maxQuantity: null, discountPercentage: 22 },
    ],
    variantTypeIds: ['var_colour', 'var_branding'],
    createdAt: '2026-01-20T00:00:00Z',
    updatedAt: '2026-01-20T00:00:00Z',
  },

  // --- EXECUTIVE GIFTWARE & TECH ---
  {
    id: 'prod_not_1',
    sku: 'NOT-A5',
    name: 'Executive Hardcover A5 Branded Notebook',
    description: 'Thermo PU leatherette hardcover notebook, 160 lined pages with ribbon marker and elastic closure.',
    basePrice: 95.00,
    categoryId: 'cat_stationery',
    isActive: true,
    images: [
      'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1531346878377-a5be20888e57?w=800&auto=format&fit=crop&q=80',
    ],
    volumeTiers: [
      { id: 'vt_n1_1', minQuantity: 1, maxQuantity: 24, discountPercentage: 0 },
      { id: 'vt_n1_2', minQuantity: 25, maxQuantity: 99, discountPercentage: 12 },
      { id: 'vt_n1_3', minQuantity: 100, maxQuantity: null, discountPercentage: 22 },
    ],
    variantTypeIds: ['var_colour'],
    createdAt: '2026-01-21T00:00:00Z',
    updatedAt: '2026-01-21T00:00:00Z',
  },
  {
    id: 'prod_pen_1',
    sku: 'PEN-EXEC',
    name: 'Executive Metal Ballpoint Pen Gift Set',
    description: 'Heavyweight brass metallic pen with German ink refill in a presentation box. Laser engraved logo.',
    basePrice: 125.00,
    categoryId: 'cat_stationery',
    isActive: true,
    images: [
      'https://images.unsplash.com/photo-1585336261026-8f5786372969?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1583485088034-697b5bc54ccd?w=800&auto=format&fit=crop&q=80',
    ],
    volumeTiers: [
      { id: 'vt_p1_1', minQuantity: 1, maxQuantity: 24, discountPercentage: 0 },
      { id: 'vt_p1_2', minQuantity: 25, maxQuantity: 99, discountPercentage: 15 },
      { id: 'vt_p1_3', minQuantity: 100, maxQuantity: null, discountPercentage: 25 },
    ],
    variantTypeIds: ['var_colour'],
    createdAt: '2026-01-22T00:00:00Z',
    updatedAt: '2026-01-22T00:00:00Z',
  },
  {
    id: 'prod_tch_1',
    sku: 'TECH-PWR',
    name: '10,000mAh Ultra-Slim Fast Power Bank',
    description: 'Lithium polymer high-capacity portable charger with dual USB outputs and digital LED battery indicator.',
    basePrice: 260.00,
    categoryId: 'cat_tech',
    isActive: true,
    images: [
      'https://images.unsplash.com/photo-1609091839311-d5365f9ff1c5?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1583863788434-e58a36330cf0?w=800&auto=format&fit=crop&q=80',
    ],
    volumeTiers: [
      { id: 'vt_t1_1', minQuantity: 1, maxQuantity: 19, discountPercentage: 0 },
      { id: 'vt_t1_2', minQuantity: 20, maxQuantity: 49, discountPercentage: 10 },
      { id: 'vt_t1_3', minQuantity: 50, maxQuantity: null, discountPercentage: 20 },
    ],
    variantTypeIds: ['var_colour'],
    createdAt: '2026-01-23T00:00:00Z',
    updatedAt: '2026-01-23T00:00:00Z',
  },
  {
    id: 'prod_lan_1',
    sku: 'PROMO-LAN',
    name: 'Sublimated Satin Lanyard with Safety Breakaway',
    description: '20mm smooth polyester satin ribbon lanyard with full-colour heat transfer print and lobster hook clasp.',
    basePrice: 28.00,
    categoryId: 'cat_stationery',
    isActive: true,
    images: [
      'https://images.unsplash.com/photo-1534215754734-18e55d13e346?w=800&auto=format&fit=crop&q=80',
    ],
    volumeTiers: [
      { id: 'vt_l1_1', minQuantity: 1, maxQuantity: 99, discountPercentage: 0 },
      { id: 'vt_l1_2', minQuantity: 100, maxQuantity: 249, discountPercentage: 15 },
      { id: 'vt_l1_3', minQuantity: 250, maxQuantity: null, discountPercentage: 30 },
    ],
    variantTypeIds: ['var_colour'],
    createdAt: '2026-01-24T00:00:00Z',
    updatedAt: '2026-01-24T00:00:00Z',
  },
];

// OVERVIEW CARDS MUST START AT ZERO AS REQUESTED BY USER
export const INITIAL_QUOTES: Quote[] = [];
